// <auto-generated />
using System;
using LessonNoteAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LessonNoteAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317061413_SeedDataUpdate")]
    partial class SeedDataUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LessonNoteAPI.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 3, 17, 9, 14, 12, 925, DateTimeKind.Local).AddTicks(318),
                            Description = "Bu bir örnek nottur. Sistemin çalıştığını kanıtlar.",
                            IsDeleted = false,
                            Title = "Hoş Geldiniz! ✨",
                            UpdatedDate = new DateTime(2026, 3, 17, 9, 14, 12, 925, DateTimeKind.Local).AddTicks(314),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 3, 17, 9, 14, 12, 925, DateTimeKind.Local).AddTicks(321),
                            Description = "Seeder verileri başarıyla yüklendi, her şey yolunda.",
                            IsDeleted = false,
                            Title = "Mülakat Hazırlığı 📚",
                            UpdatedDate = new DateTime(2026, 3, 17, 9, 14, 12, 925, DateTimeKind.Local).AddTicks(320),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("LessonNoteAPI.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "test@nursima.com",
                            FullName = "Nursima Test",
                            Password = "123"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
